server:
  port: 8380

spring:
  application:
    name: service-fegin

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/

