#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.demo.model
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://10.100.156.66:3306/redis_mybatise
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
      host: 10.100.156.66
      port: 6379
      password: root
      pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
